{
    "window.customTitleBarVisibility": "never",
    "telemetry.telemetryLevel": "off",
    "workbench.sideBar.location": "right",
    "files.autoSave": "afterDelay",
    "editor.fontFamily": "FiraCode Nerd Font",
    "editor.renderWhitespace": "all",
    "editor.fontLigatures": true,
    "window.nativeTabs": true,
    "notebook.lineNumbers": "on",
    "notebook.output.scrolling": true,
    "python.defaultInterpreterPath": "/Users/alperenunlu/miniforge3/envs/deep/bin/python",
    "jupyter.askForKernelRestart": false,
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false
    },
    "github.copilot.enable": {
        "*": true,
        "plaintext": false,
        "markdown": false,
        "scminput": false
    },
    "mypy-type-checker.args": [
        "--disable-error-code=import-untyped"
    ],
    "mypy-type-checker.reportingScope": "workspace",
}
